---
core:
    num_workers: 100
inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "./inventory/hosts.yml"
        group_file: "./inventory/group.yml"