---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "./inventory/hosts.yml"
        group_file: "./inventory/group.yml"

runners:
    plugin: threaded
    options:
        num_workers: 20