---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "./inventory/hosts.yml"
        group_file: "./inventory/group.yml"

runners:
    plugin: threaded # povolení paralelismu (registrace threaded pluginu)
    options:
        num_workers: 20 #20 použitých vláken pro daný Task