---
interfaces_ipv4: # nastavení IPv4 rozhraní, router_physical_port: true - pokud to není Loopback
  FastEthernet0/0:
      description: connected to R2 on port em1
      net: 192.168.2.1
      mask: 255.255.255.0
      routed_physical_port: true
      duplex: full
      speed: auto
  FastEthernet0/1:
      description: connected to SW1 on port e0
      net: 192.168.1.1
      mask: 255.255.255.0
      routed_physical_port: true
      duplex: full
      speed: auto
ospf_config: # OSPFv2 konfigurace + redistribuce
    process: 1
    router_id: 1.1.1.1
    passive_interfaces: [ FastEthernet0/1 ]
    networks:
        - ip: 192.168.1.0
          wildcard: 0.0.0.255
          area_number: 0
        - ip: 192.168.2.0
          wildcard: 0.0.0.255
          area_number: 0
interfaces_ipv6: # Základní nastavení rozhraní - IPv6
    FastEthernet0/0:
        description: connected to R2 on port em1
        networks:
            - net: "2001:db8:1001:2::1"
              prefix_length: /64
              eui_format_auto: false
        routed_physical_port: true
        duplex: full
        speed: auto
    FastEthernet0/1:
        description: connected to SW1 on port e0
        networks:
            - net: "2001:db8:1001:1::1"
              prefix_length: /64
              eui_format_auto: false
        routed_physical_port: true
        duplex: full
        speed: auto
ospfv3_config: # OSPFv3 konfigurace + redistribuce
    process: 1
    router_id: 1.1.1.1
    passive_interfaces: [ FastEthernet0/1 ]
    interfaces:
      - name: FastEthernet0/0
        area_number: 0
      - name: FastEthernet0/1
        area_number: 0
restore_config:
    running_config_date: 2021-04-07
delete_config:
    interfaces: # routované porty
        physical: [FastEthernet0/0, FastEthernet0/1] # resetování nastavení fyzického rozhraní do výchozího stavu
    ospf_config:
        processes: [1]
    ospfv3_config:
        processes:
            - number: 1
              interfaces:
                - name: FastEthernet0/0
                  area_number: 0
                - name: FastEthernet0/1
                  area_number: 0