---
interfaces_ipv4: # nastavení IPv4 rozhraní, router_physical_port: true - pokud to není Loopback
  FastEthernet0/0:
      description: connected to R2 on port em2
      net: 192.168.3.2
      mask: 255.255.255.0
      routed_physical_port: true
      duplex: full
      speed: auto
  FastEthernet0/1:
      description: connected to MLS1 on port g0/1
      net: 192.168.4.1
      mask: 255.255.255.0
      routed_physical_port: true
      duplex: full
      speed: auto
ospf_config: # OSPFv2 konfigurace + redistribuce
    process: 1
    router_id: 3.3.3.3
    networks:
        - ip: 192.168.3.0
          wildcard: 0.0.0.255
          area_number: 0
    redistribute:
      static: false
      default: false
      eigrp:
        AS_numbers: [1]
eigrp_config: # EIGRP konfigurace + redistribuce (static, ospf), nepovinné fieldy: passive_interfaces, redistribute
  AS_number: 1
  passive_interfaces: []
  networks:
    - ip: 192.168.4.0
      wildcard: 0.0.0.255
  redistribute:
    ospf:
      processes:
        - number: 1
          bandwidth: 1000000
          delay: 1
          reliability: 255
          load: 1
          mtu: 1500
interfaces_ipv6: # Základní nastavení rozhraní - IPv6
    FastEthernet0/0:
        description: connected to R2 on port em2
        networks:
            - net: "2001:db8:1001:3::2"
              prefix_length: /64
              eui_format_auto: false
        routed_physical_port: true
        duplex: full
        speed: auto
    FastEthernet0/1:
        description: connected to MLS1 on port g0/1
        networks:
            - net: "2001:db8:1001:4::1"
              prefix_length: /64
              eui_format_auto: false
        routed_physical_port: true
        duplex: full
        speed: auto
ospfv3_config: # OSPFv3 konfigurace + redistribuce
    process: 1
    router_id: 3.3.3.3
    interfaces:
      - name: FastEthernet0/0
        area_number: 0
    redistribute:
      static: false
      default: false
      eigrp:
        AS_numbers: [1]
restore_config:
    running_config_date: 2021-04-07
eigrp_ipv6_config: # EIGRP IPv6 konfigurace
  AS_number: 1
  router_id: 3.3.3.3
  passive_interfaces: []
  interfaces: [ FastEthernet0/1 ]
  redistribute:
    ospf:
      processes:
        - number: 1
          bandwidth: 1000000
          delay: 1
          reliability: 255
          load: 1
          mtu: 1500
delete_config:
    interfaces: # routované porty
        physical: [FastEthernet0/0, FastEthernet0/1] # resetování nastavení fyzického rozhraní do výchozího stavu
    eigrp_config:
      AS_numbers: [ 1 ]
    eigrp_ipv6_config:
      AS:
        - number: 1
          interfaces: [ FastEthernet0/1 ]
    ospf_config:
        processes: [1]
    ospfv3_config:
        processes:
            - number: 1
              interfaces:
                - name: FastEthernet0/0
                  area_number: 0
                - name: FastEthernet0/1
                  area_number: 0