---
commands: ["pwd", "ls"]
vsftpd_config:
  # (S)FTP konfigurace - vsftpd, nutné mít vytvořeného FTP usera (v mém případě ftpuser) a v případě SSL vygenerovaný certifikát
  # V případě SSL je nutné mít předem vygenerovaný certifikát (např. self-signed). Předem jsem vytvořil složku /etc/certs.
  # Self-signed certifikat: sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/certs/vsftpd.pem -out /etc/certs/vsftpd.pem
  ssl:
    enabled: true
    rsa_cert_file: /etc/certs/vsftpd.pem
    rsa_private_key_file: /etc/certs/vsftpd.pem
  commands:
   #- "apt update" - doporučuji vynechat a provést manuálně. V opačném případě musítě upravit v groups.yml parametr global_delay_factor pro linux group. Parametr nastavte minimálně na hodnotu 5.
    - "apt-get install vsftpd -y"
    - "systemctl start vsftpd"
    - "systemctl enable vsftpd"
    - "mkdir /home/ftpuser/ftp"
    - "chown nobody:nogroup /home/ftpuser/ftp"
    - "chmod a-w /home/ftpuser/ftp"
    - "mkdir /home/ftpuser/ftp/test"
    - "chown ftpuser:ftpuser /home/ftpuser/ftp/test"
    - "cp /etc/vsftpd.conf /etc/vsftpd.conf.bak"
    - "rm /etc/vsftpd.conf"
    - "scp" # zvolený příkaz, ve skriptu bude tento příkaz kontrolován. Pokud nastane, tak se spustí netmiko_file_transfer task (SCP) pro překopírování vsftpd.conf
    - "echo ftpuser | sudo tee -a /etc/vsftpduserlist.conf"
    - "systemctl restart vsftpd"
  testing:
    host: 10.10.10.10
    user: ftpuser
    password: ftpuser # plain-text heslo pro zjednodušení testování (parsování citlivých dat šifrovaných v Ansible Vault bylo provedeno pouze pro groups.yml).
    base_directory: test
    test_folder: python_testing
