---
vlans_config:
  - number: 10
    name: VLAN10
  - number: 20
    name: AdminVLAN
switching_interfaces: # konfigurace switchportů
  GigabitEthernet0/1:
    description: popis rozhrani
    mode: access
    vlan: 10
    duplex: full
  GigabitEthernet0/2:
    description: popis rozhrani
    mode: trunk
    trunk_vlans: 10,20
    duplex: full
    speed: auto
interfaces_ipv4: # konfigurace routing portů + VLAN (SVI) - IPv4, pokud fyzické rozhraní bude routované (no switchport), tak musí být definovaný klíč routed_physical_port.
  Loopback0:
    description: popis rozhrani
    net: 192.168.41.1
    mask: 255.255.255.0
  GigabitEthernet0/3:
    description: popis rozhrani
    net: 192.168.70.1
    mask: 255.255.255.0
    routed_physical_port: true
    duplex: full
  GigabitEthernet1/0:
    description: popis rozhrani
    net: 192.168.80.3
    mask: 255.255.255.0
    routed_physical_port: true
    duplex: full
  Vlan10:
    description: popis rozhrani
    net: 192.168.10.3
    mask: 255.255.255.0
static_routing_config: # IPv4 statický routing
  networks:
      - dest_ip: 192.168.38.0
        dest_mask: 255.255.255.0
        next_hop: 192.168.60.2
      - dest_ip: 192.168.45.0
        dest_mask: 255.255.255.0
        next_hop: 192.168.60.2
  default:
      next_hop: 192.168.10.2
ospf_config: # OSPFv2 konfigurace + redistribuce
  process: 3
  router_id: 5.5.5.5
  passive_interfaces: [ GigabitEthernet1/0 ]
  networks:
      - ip: 192.168.16.0
        wildcard: 0.0.0.255
        area_number: 0
      - ip: 192.168.52.0
        wildcard: 0.0.0.3
        area_number: 0
  redistribute:
      static: true
      default: true
      eigrp:
          AS_numbers: [ 1, 2, 3 ]
eigrp_config: # EIGRP konfigurace + redistribuce
  AS_number: 4
  passive_interfaces: [ GigabitEthernet1/0 ]
  networks:
      - ip: 192.168.10.0
        wildcard: 0.0.0.255
      - ip: 192.168.60.0
        wildcard: 0.0.0.255
  redistribute:
      static: true
      ospf:
          processes: [1, 2, 3, 4]
packet_filter_config: # Named ACL konfigurace standard + extended
  ADMIN-ACL:
      type: extended
      rules:
          - deny ip 192.168.10.0 0.0.0.255 192.168.20.0 0.0.0.255
          - deny ip 192.168.30.0 0.0.0.255 192.168.20.0 0.0.0.255
          - deny ip 192.168.50.0 0.0.0.255 192.168.20.0 0.0.0.255
          - permit ip any any
      routed_interfaces:
          - name: GigabitEthernet0/3
            acl_direction: in
  Student-ACL:
      type: standard
      rules:
          - permit 172.30.0.0 0.0.255.255
          - deny 192.168.1.53
      routed_interfaces:
          - name: GigabitEthernet1/0
            acl_direction: out
nat_overload_config: # source NAT typu PAT
  access_list_number: 2
  source_network:
      ip: 192.168.0.0
      wild_card: 0.0.0.255
  interface_types:
      inside:
          routed_port: GigabitEthernet0/3
      outside:
          routed_port: GigabitEthernet1/0
interfaces_ipv6: # konfigurace routing portů + VLAN - IPv6
  GigabitEthernet1/1:
      description: popis
      networks:
          - net: "2001:bb9:aabb:1234:1111:2222:3333:4445"
            prefix_length: /64
            eui_format_auto: false
          - net: "2001:bb9:aabb:1235::"
            prefix_length: /64
            eui_format_auto: true  # povolení IEEE EUI-64 metody kalkulace IPv6 adresy
      routed_physical_port: true
      duplex: full
      speed: auto
  GigabitEthernet1/2:
      description: popis rozhrani
      networks:
          - net: "2001:718:6::2"
            prefix_length: /64
            eui_format_auto: false
      routed_physical_port: true
      duplex: full
  Vlan10:
      description: popis rozhrani
      networks:
          - net: "2001:718:3::2"
            prefix_length: /64
            eui_format_auto: false
static_routing_ipv6_config:
  networks:
      - dest_ip: "2001:db8::"
        prefix_length: /32
        next_hop: "2001:bb9:aabb:1234:1111:2222:3333:4445"
      - dest_ip: "2001:db9::"
        prefix_length: /32
        next_hop: GigabitEthernet1/1
  default:
      next_hop: "2001:718:1::3"
eigrp_ipv6_config: # EIGRP konfigurace + redistribuce - IPv6
  AS_number: 1
  router_id: 3.3.3.3
  passive_interfaces: [ GigabitEthernet1/1 ]
  routed_interfaces: [ Vlan10, GigabitEthernet1/2 ]
  redistribute:
      static: true
packet_filter_ipv6_config: # Named ACL konfigurace - IPv6, lze pouze u ROUTED (no switchport) rozhraní
  ACLName:
      rules:
          - permit ipv6 any any
      routed_interfaces:
          - name: GigabitEthernet1/1
            acl_direction: out
  ExampleACL:
      rules:
          - permit icmp 2001:db8:e0bb::/64 2001:db8::/64
          - permit ipv6 any any
      routed_interfaces:
          - name: GigabitEthernet1/2
            acl_direction: in
restore_config:
  running_config_date: 2020-12-20
delete_config:
  interfaces:
      virtual: [Vlan10, Loopback0] # úplné vymázání virtuálních síťových rozhraní
      physical: [GigabitEthernet0/1, GigabitEthernet0/2, GigabitEthernet0/3, GigabitEthernet1/0, GigabitEthernet1/1, GigabitEthernet1/2] # resetování nastavení fyzických rozhraní do výchozího stavu
  static_routing_config: true
  ospf_config:
      processes: [1, 3]
  eigrp_config:
      AS_numbers: [4]
  packet_filter_config:
      ADMIN-ACL:
          type: extended
          routed_interfaces:
              - name: GigabitEthernet0/3
                acl_direction: in
      Student-ACL:
          type: standard
          routed_interfaces:
              - name: GigabitEthernet1/0
                acl_direction: out
  static_routing_ipv6_config:
      networks:
          - dest_ip: "2001:db8::"
            prefix_length: /32
            next_hop: "2001:bb9:aabb:1234:1111:2222:3333:4445"
      default:
          next_hop: "2001:718:1::3"
  eigrp_ipv6_config:
      AS:
          - number: 1
            routed_interfaces: [ Vlan10, GigabitEthernet1/2 ]
  packet_filter_ipv6_config:
      ACLName:
          routed_interfaces:
              - name: GigabitEthernet1/1
                acl_direction: out
      ExampleACL:
          routed_interfaces:
              - name: GigabitEthernet1/2
                acl_direction: in
  nat_overload_config:
      access_list_number: 2
      interface_types:
          inside:
              routed_port: GigabitEthernet0/3
          outside:
              routed_port: GigabitEthernet1/0
  vlans_config:
      numbers: [10, 20]