---
cisco_group:
  platform: "ios"
  username: "cisco"
  password: "cisco"
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: "cisco"

junos_group:
  platform: "junos"
  username: "juniper"
  password: "Juniper"

linux_group:
  platform: "linux"
  username: "root"
  password: "root"

test:
  platfo: test
