---
cisco:
  platform: "ios" # pro napalm/netmiko driver (ovladač)
  connection_options:
    napalm:
      extras:
        optional_args:
          global_delay_factor: 1 # prodlužuje čas na provedení daného příkazu. Pro global_delay_factor: X (kladné číslo) platí následující doba čekání: X * 100s
    netmiko:
      extras:
        global_delay_factor: 1 # prodlužuje čas na provedení daného příkazu. Pro global_delay_factor: X (kladné číslo) platí následující doba čekání: X * 100s

juniper:
  platform: "junos" # pro napalm/netmiko driver (ovladač)

linux:
  platform: "linux" # pro netmiko driver
  connection_options:
    netmiko:
      extras:
        global_delay_factor: 3 # prodlužuje čas na provedení daného příkazu. Pro global_delay_factor: X (kladné číslo) platí následující doba čekání: X * 100s

