---
cisco:
  platform: "ios" # pro napalm/netmiko driver (ovladač)
  connection_options:
    napalm:
      extras:
        optional_args:
          auto_file_prompt: True
          global_delay_factor: 1
    netmiko:
      extras:
        global_delay_factor: 1

juniper:
  platform: "junos" # pro napalm/netmiko driver (ovladač)

linux:
  platform: "linux" # pro netmiko driver
  connection_options:
    netmiko:
      extras:
        global_delay_factor: 3

