---
cisco_group:
  platform: "ios"
  username: "cisco"
  password: "cisco"

junos_group:
  platform: "juniper_junos"
  username: "root"
  password: "Juniper"

linux_group:
  platform: "linux"
  username: "root"
  password: "root"
