---
cisco:
  platform: "ios"
  connection_options:
    napalm:
      extras:
        optional_args:
          auto_file_prompt: True
          global_delay_factor: 1
    netmiko:
      extras:
        global_delay_factor: 1

juniper:
  platform: "junos"

linux:
  platform: "linux"
  connection_options:
    netmiko:
      extras:
        global_delay_factor: 3

