---
cisco_group:
  platform: "ios"
  username: "admin"
  password: "cisco"
  connection_options:
    napalm:
      extras:
        optional_args:
          secret: "cisco"
          auto_file_prompt: True
          #global_delay_factor: 2
    netmiko:
      extras:
        secret: "cisco"
        #lobal_delay_factor: 2

junos_group:
  platform: "junos"
  username: "juniper"
  password: "Juniper"

linux_group:
  platform: "linux"
  username: "linux"
  password: "linux"

